import type { FluidPreset } from './types';

const defaultReferenceTemperatureC = 20;

/**
 * Typical engineering values near ambient conditions.
 * Intended for initialization only; users can override all fields.
 */
export const FLUID_PRESETS: readonly FluidPreset[] = [
  {
    id: 'water',
    name: 'Вода',
    density_kg_m3: 998,
    dynamicViscosity_Pa_s: 0.001002,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Чистая вода при ~20°C.',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.024, minViscosityPaS: 0.0002 },
  },
  {
    id: 'hydrochloric-acid',
    name: 'Соляная кислота',
    density_kg_m3: 1190,
    dynamicViscosity_Pa_s: 0.0019,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Типовой водный раствор HCl средней концентрации (~30%).',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.02, minViscosityPaS: 0.0004 },
  },
  {
    id: 'caustic-soda',
    name: 'Каустическая сода',
    density_kg_m3: 1330,
    dynamicViscosity_Pa_s: 0.012,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Типовой водный раствор NaOH (~30%).',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.03, minViscosityPaS: 0.001 },
  },
  {
    id: 'ethylene-glycol',
    name: 'Этиленгликоль',
    density_kg_m3: 1110,
    dynamicViscosity_Pa_s: 0.0161,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Чистый этиленгликоль при ~20°C.',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.036, minViscosityPaS: 0.001 },
  },
  {
    id: 'ethanol',
    name: 'Спирт (этанол)',
    density_kg_m3: 789,
    dynamicViscosity_Pa_s: 0.0012,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Безводный этанол при ~20°C.',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.022, minViscosityPaS: 0.0003 },
  },
  {
    id: 'acetone',
    name: 'Ацетон',
    density_kg_m3: 784,
    dynamicViscosity_Pa_s: 0.00032,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Ацетон при ~20°C.',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.018, minViscosityPaS: 0.00015 },
  },
  {
    id: 'diesel-fuel',
    name: 'Дизтопливо',
    density_kg_m3: 832,
    dynamicViscosity_Pa_s: 0.0035,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Типовое дизельное топливо при ~20°C.',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.032, minViscosityPaS: 0.001 },
  },
  {
    id: 'mineral-oil',
    name: 'Минеральное масло',
    density_kg_m3: 870,
    dynamicViscosity_Pa_s: 0.065,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Индустриальное минеральное масло ISO VG порядка 68.',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.04, minViscosityPaS: 0.003 },
  },
  {
    id: 'glycerin',
    name: 'Глицерин',
    density_kg_m3: 1260,
    dynamicViscosity_Pa_s: 1.49,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Чистый глицерин при ~20°C; сильная температурная зависимость.',
    viscosityModel: { kind: 'exponential', coefficientPerC: 0.055, minViscosityPaS: 0.01 },
  },
  {
    id: 'custom',
    name: 'Пользовательская жидкость',
    density_kg_m3: 1000,
    dynamicViscosity_Pa_s: 0.001,
    temperature_C: defaultReferenceTemperatureC,
    referenceTemperature_C: defaultReferenceTemperatureC,
    isNewtonian: true,
    notes: 'Заполните свойства вручную на основе ваших данных.',
  },
] as const;
