import { useAppStore } from '../../store/useAppStore';

const mediumLabel: Record<string, string> = { none: 'нет', mixed: 'смешанная', water: 'вода', product: 'продукт', cip: 'CIP', waste: 'сток' };

export const SimulationPanel = () => {
  const project = useAppStore((state) => state.project); const selectedNodeId = useAppStore((state) => state.selectedNodeId); const selectedEdgeId = useAppStore((state) => state.selectedEdgeId); const setSimulationRunning = useAppStore((state) => state.setSimulationRunning); const setSimulationSpeed = useAppStore((state) => state.setSimulationSpeed); const toggleProblematicOnly = useAppStore((state) => state.toggleProblematicOnly); const issues = useAppStore((state) => state.issues); const showProblematicOnly = useAppStore((state) => state.showProblematicOnly);
  const selectedNode = project.nodes.find((node) => node.id === selectedNodeId); const selectedEdge = project.edges.find((edge) => edge.id === selectedEdgeId); const warningCount = issues.filter((issue) => issue.severity !== 'info').length;
  return <div className="simulation-panel"><div className="sim-header"><div><strong>Состояние технологической схемы</strong><span>Панель показывает поток, блокировки и диагностические предупреждения по текущей схеме.</span></div><div className="sim-pills"><span className="sim-pill">{project.simulation.running ? 'Симуляция включена' : 'Режим редактирования'}</span><span className="sim-pill">Предупреждения: {warningCount}</span><span className="sim-pill">Поток: {Math.round(project.simulation.totalActiveFlow)} л/мин</span></div></div><div className="sim-controls"><button onClick={() => setSimulationRunning(!project.simulation.running)}>{project.simulation.running ? 'Пауза' : 'Пуск'}</button><label><span>Скорость {project.simulation.speed.toFixed(1)}x</span><input type="range" min="0.5" max="3" step="0.5" value={project.simulation.speed} onChange={(e) => setSimulationSpeed(Number(e.target.value))} /></label><button onClick={toggleProblematicOnly}>{showProblematicOnly ? 'Показать всё' : 'Только проблемные'}</button></div><div className="status-strip compact"><span><strong>Среда:</strong> {mediumLabel[project.simulation.activeMedium]}</span><span><strong>Последнее событие:</strong> {project.simulation.lastEvent}</span><span><strong>Выбор:</strong> {selectedNode ? `${selectedNode.data.visibleName} • ${selectedNode.data.technicalTag}` : selectedEdge ? `${selectedEdge.data?.sourceLabel} → ${selectedEdge.data?.targetLabel}` : 'ничего не выбрано'}</span></div></div>;
};
