import { useAppStore } from '../../store/useAppStore';

const speedOptions = [0.5, 1, 1.5, 2, 3];

const mediumLabel: Record<string, string> = { none: 'нет', mixed: 'смешанная', water: 'вода', product: 'продукт', cip: 'CIP', waste: 'сток' };

export const SimulationPanel = () => {
  const project = useAppStore((state) => state.project); const selectedNodeId = useAppStore((state) => state.selectedNodeId); const selectedEdgeId = useAppStore((state) => state.selectedEdgeId); const setSimulationRunning = useAppStore((state) => state.setSimulationRunning); const setSimulationSpeed = useAppStore((state) => state.setSimulationSpeed); const resetSimulation = useAppStore((state) => state.resetSimulation); const toggleProblematicOnly = useAppStore((state) => state.toggleProblematicOnly); const issues = useAppStore((state) => state.issues); const showProblematicOnly = useAppStore((state) => state.showProblematicOnly);
  const selectedNode = project.nodes.find((node) => node.id === selectedNodeId); const selectedEdge = project.edges.find((edge) => edge.id === selectedEdgeId); const warningCount = issues.filter((issue) => issue.severity !== 'info').length;
  const recentEvents = project.eventLog.slice(-6).reverse();
  const activeWarnings = project.simulation.warnings.slice(0, 3);
  return <div className="simulation-panel"><div className="sim-header"><div><strong>Состояние технологической схемы</strong><span>Панель показывает поток, блокировки и диагностические предупреждения по текущей схеме.</span></div><div className="sim-pills"><span className="sim-pill">{project.simulation.running ? 'Симуляция включена' : 'Режим редактирования'}</span><span className="sim-pill">Предупреждения: {warningCount}</span><span className="sim-pill">Поток: {Math.round(project.simulation.totalActiveFlow)} л/мин</span></div></div><div className="sim-controls"><div className="sim-control-group"><button onClick={() => setSimulationRunning(true)} disabled={project.simulation.running}>▶ Пуск</button><button onClick={() => setSimulationRunning(false)} disabled={!project.simulation.running}>❚❚ Пауза</button><button onClick={resetSimulation}>↺ Сброс</button></div><div className="sim-control-group sim-speed-group"><span>Скорость</span>{speedOptions.map((speed) => <button key={speed} className={project.simulation.speed === speed ? 'is-selected' : ''} onClick={() => setSimulationSpeed(speed)}>{speed.toFixed(speed % 1 === 0 ? 0 : 1)}x</button>)}</div><button onClick={toggleProblematicOnly}>{showProblematicOnly ? 'Показать всё' : 'Только проблемные'}</button></div><div className="status-grid"><div className="status-card"><span>Среда</span><strong>{mediumLabel[project.simulation.activeMedium]}</strong></div><div className="status-card"><span>Последнее событие</span><strong>{project.simulation.lastEvent}</strong></div><div className="status-card"><span>Активные предупреждения</span><strong>{warningCount}</strong><small>{activeWarnings[0] ?? 'Нет активных предупреждений'}</small></div><div className="status-card"><span>Выбор</span><strong>{selectedNode ? `${selectedNode.data.visibleName} • ${selectedNode.data.technicalTag}` : selectedEdge ? `${selectedEdge.data?.sourceLabel} → ${selectedEdge.data?.targetLabel}` : 'ничего не выбрано'}</strong></div></div><div className="warning-strip">{activeWarnings.length ? activeWarnings.map((warning) => <span key={warning} className="warning-pill">{warning}</span>) : <span className="warning-pill is-idle">Активных предупреждений нет</span>}</div><div className="event-log-card"><div className="event-log-head"><strong>Журнал событий</strong><span>Буфер: {project.eventLog.length}</span></div><div className="event-log-list">{recentEvents.map((event) => <div key={event.id} className={`event-log-item severity-${event.severity}`}><span>{new Date(event.timestamp).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit', second: '2-digit', timeZone: 'UTC' })}</span><strong>{event.message}</strong></div>)}</div></div></div>;
};
